name: qatar22
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  cached_network_image: any
  intl: ^0.17.0
  google_fonts: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: any
  group_list_view: 

module:
  androidX: true  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/png/
     - assets/info/
     - assets/icons/


  #    - assets/images/qatar1.jpg
  #    - assets/images/qatar3.png
  #    - assets/images/logo2.svg
  # #   - images/a_dot_ham.jpeg
  #    - assets/images/img.jpg
  #    - assets/images/biden2.jpg
  #    - assets/images/messi.jpg
  #    - assets/images/joeRogan2.jpg
  #    - assets/images/skyNews.png
  #    - assets/images/spotify.png
  #    - assets/images/img1.jpg
  #    - assets/images/img7.jpg
  #    - assets/images/img3.jpeg
  #    - assets/images/img5.jpg
  #    - assets/images/argantine.png
  #    - assets/images/arabic.png
  #    - assets/images/belguim.png
  #    - assets/images/croitia.png
  #    - assets/images/england.png
  #    - assets/images/espagna.png
  #    - assets/images/france.png
  #    - assets/images/germany.png
  #    - assets/images/italia.png
  #    - assets/images/japon.png
  #    - assets/images/poland.png
  #    - assets/images/portogal.png
  #    - assets/images/tunisie.png
  #    - assets/images/wales.png
  #    - assets/images/qatar.png
  #    - assets/images/brazil.png
  #    - assets/images/qatar1.png
     - assets/images/
 
     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
